-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglcRou6hD4X6FXhNa
3TFA0csPRftTrI9gLUK6U3mAofmgCgYIKoZIzj0DAQehRANCAARNthuHEQXv+ayP
0TKnpEaR+Vk22XxvpzlyLdcJueWrd6Z0/kRVEUryH9abaoIUY6U+hVASignss9zi
NxYLK4XA
-----END PRIVATE KEY-----